on: [pull_request]
auto-merge:
    permissions:
        contents: write
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
        - uses: fastify/github-action-merge-dependabot@v3.2
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              target: minor
